/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createJwksFromDiscriminatorValue, serializeJwks, type Jwks } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {KeysGetResponse}
 */
// @ts-ignore
export function createKeysGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoKeysGetResponse;
}
/**
 * The deserialization information for the current model
 * @param KeysGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoKeysGetResponse(keysGetResponse: Partial<KeysGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "keys": n => { keysGetResponse.keys = n.getCollectionOfObjectValues<Jwks>(createJwksFromDiscriminatorValue); },
    }
}
export interface KeysGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * The keys property
     */
    keys?: Jwks[] | null;
}
/**
 * Builds and executes requests for operations under /authentication/v2/keys
 */
export interface KeysRequestBuilder extends BaseRequestBuilder<KeysRequestBuilder> {
    /**
     * To return JSON Web Key Set that used to validate JWT token.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<KeysGetResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<KeysGetResponse | undefined>;
    /**
     * To return JSON Web Key Set that used to validate JWT token.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param KeysGetResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeKeysGetResponse(writer: SerializationWriter, keysGetResponse: Partial<KeysGetResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!keysGetResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Jwks>("keys", keysGetResponse.keys, serializeJwks);
    writer.writeAdditionalData(keysGetResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const KeysRequestBuilderUriTemplate = "{+baseurl}/authentication/v2/keys";
/**
 * Metadata for all the requests in the request builder.
 */
export const KeysRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: KeysRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createKeysGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
