/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { JobsRequestBuilderNavigationMetadata, JobsRequestBuilderRequestsMetadata, type JobsRequestBuilder } from './jobs/index.js';
// @ts-ignore
import { RequestsRequestBuilderNavigationMetadata, RequestsRequestBuilderRequestsMetadata, type RequestsRequestBuilder } from './requests/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /accounts/{accountId}
 */
export interface WithAccountItemRequestBuilder extends BaseRequestBuilder<WithAccountItemRequestBuilder> {
    /**
     * The jobs property
     */
    get jobs(): JobsRequestBuilder;
    /**
     * The requests property
     */
    get requests(): RequestsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithAccountItemRequestBuilderUriTemplate = "{+baseurl}/accounts/{accountId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithAccountItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithAccountItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    jobs: {
        requestsMetadata: JobsRequestBuilderRequestsMetadata,
        navigationMetadata: JobsRequestBuilderNavigationMetadata,
    },
    requests: {
        requestsMetadata: RequestsRequestBuilderRequestsMetadata,
        navigationMetadata: RequestsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
