/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type UsersImportRequestBuilder, UsersImportRequestBuilderRequestsMetadata } from './usersImport/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /construction/admin/v2/projects/{projectId}
 */
export interface WithProjectItemRequestBuilder extends BaseRequestBuilder<WithProjectItemRequestBuilder> {
    /**
     * The usersImport property
     */
    get usersImport(): UsersImportRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithProjectItemRequestBuilderUriTemplate = "{+baseurl}/construction/admin/v2/projects/{projectId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithProjectItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithProjectItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    usersImport: {
        requestsMetadata: UsersImportRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
