/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface AuthToken extends AdditionalDataHolder, Parsable {
    /**
     * The access_token property
     */
    accessToken?: string | null;
    /**
     * The expires_in property
     */
    expiresIn?: number | null;
    /**
     * The id_token property
     */
    idToken?: string | null;
    /**
     * The refresh_token property
     */
    refreshToken?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AuthToken}
 */
// @ts-ignore
export function createAuthTokenFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAuthToken;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorEscaped}
 */
// @ts-ignore
export function createErrorEscapedFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorEscaped;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Introspecttoken}
 */
// @ts-ignore
export function createIntrospecttokenFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIntrospecttoken;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Jwks}
 */
// @ts-ignore
export function createJwksFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJwks;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OidcSpec}
 */
// @ts-ignore
export function createOidcSpecFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOidcSpec;
}
/**
 * The deserialization information for the current model
 * @param AuthToken The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAuthToken(authToken: Partial<AuthToken> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "access_token": n => { authToken.accessToken = n.getStringValue(); },
        "expires_in": n => { authToken.expiresIn = n.getNumberValue(); },
        "id_token": n => { authToken.idToken = n.getStringValue(); },
        "refresh_token": n => { authToken.refreshToken = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ErrorEscaped The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorEscaped(errorEscaped: Partial<ErrorEscaped> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "developerMessage": n => { errorEscaped.developerMessage = n.getStringValue(); },
        "errorCode": n => { errorEscaped.errorCode = n.getStringValue(); },
        "more info": n => { errorEscaped.moreInfo = n.getStringValue(); },
        "userMessage": n => { errorEscaped.userMessage = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Introspecttoken The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIntrospecttoken(introspecttoken: Partial<Introspecttoken> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "active": n => { introspecttoken.active = n.getBooleanValue(); },
        "client_id": n => { introspecttoken.clientId = n.getStringValue(); },
        "exp": n => { introspecttoken.exp = n.getNumberValue(); },
        "scope": n => { introspecttoken.scope = n.getStringValue(); },
        "userid": n => { introspecttoken.userid = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Jwks The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJwks(jwks: Partial<Jwks> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "e": n => { jwks.e = n.getStringValue(); },
        "kid": n => { jwks.kid = n.getStringValue(); },
        "kty": n => { jwks.kty = n.getStringValue(); },
        "n": n => { jwks.n = n.getStringValue(); },
        "use": n => { jwks.use = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param OidcSpec The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOidcSpec(oidcSpec: Partial<OidcSpec> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "authorization_endpoint": n => { oidcSpec.authorizationEndpoint = n.getStringValue(); },
        "grant_types_supported": n => { oidcSpec.grantTypesSupported = n.getCollectionOfPrimitiveValues<string>(); },
        "id_token_signing_alg_values_supported": n => { oidcSpec.idTokenSigningAlgValuesSupported = n.getCollectionOfPrimitiveValues<string>(); },
        "introspection_endpoint": n => { oidcSpec.introspectionEndpoint = n.getStringValue(); },
        "issuer": n => { oidcSpec.issuer = n.getStringValue(); },
        "jwks_uri": n => { oidcSpec.jwksUri = n.getStringValue(); },
        "response_modes_supported": n => { oidcSpec.responseModesSupported = n.getCollectionOfPrimitiveValues<string>(); },
        "response_types_supported": n => { oidcSpec.responseTypesSupported = n.getCollectionOfPrimitiveValues<string>(); },
        "revocation_endpoint": n => { oidcSpec.revocationEndpoint = n.getStringValue(); },
        "scopes_supported": n => { oidcSpec.scopesSupported = n.getCollectionOfPrimitiveValues<string>(); },
        "subject_types_supported": n => { oidcSpec.subjectTypesSupported = n.getCollectionOfPrimitiveValues<string>(); },
        "token_endpoint": n => { oidcSpec.tokenEndpoint = n.getStringValue(); },
        "userinfo_endpoint": n => { oidcSpec.userinfoEndpoint = n.getStringValue(); },
    }
}
export interface ErrorEscaped extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * A short explanation, typically meant to assist diagnose the cause of the error
     */
    developerMessage?: string | null;
    /**
     * The errorCode property
     */
    errorCode?: string | null;
    /**
     * The moreInfo property
     */
    moreInfo?: string | null;
    /**
     * A short, generic description of the error, meant for an end-user audience.
     */
    userMessage?: string | null;
}
export type Granttype = (typeof GranttypeObject)[keyof typeof GranttypeObject];
/**
 * The response body for the introspection of access token.
 */
export interface Introspecttoken extends AdditionalDataHolder, Parsable {
    /**
     * The active property
     */
    active?: boolean | null;
    /**
     * The client_id property
     */
    clientId?: string | null;
    /**
     * The exp property
     */
    exp?: number | null;
    /**
     * The scope property
     */
    scope?: string | null;
    /**
     * The userid property
     */
    userid?: string | null;
}
export interface Jwks extends AdditionalDataHolder, Parsable {
    /**
     * The e property
     */
    e?: string | null;
    /**
     * The kid property
     */
    kid?: string | null;
    /**
     * The kty property
     */
    kty?: string | null;
    /**
     * The n property
     */
    n?: string | null;
    /**
     * The use property
     */
    use?: string | null;
}
/**
 * OIDC Specification
 */
export interface OidcSpec extends AdditionalDataHolder, Parsable {
    /**
     * The authorization_endpoint property
     */
    authorizationEndpoint?: string | null;
    /**
     * The grant_types_supported property
     */
    grantTypesSupported?: string[] | null;
    /**
     * The id_token_signing_alg_values_supported property
     */
    idTokenSigningAlgValuesSupported?: string[] | null;
    /**
     * The introspection_endpoint property
     */
    introspectionEndpoint?: string | null;
    /**
     * The issuer property
     */
    issuer?: string | null;
    /**
     * The jwks_uri property
     */
    jwksUri?: string | null;
    /**
     * The response_modes_supported property
     */
    responseModesSupported?: string[] | null;
    /**
     * The response_types_supported property
     */
    responseTypesSupported?: string[] | null;
    /**
     * The revocation_endpoint property
     */
    revocationEndpoint?: string | null;
    /**
     * The scopes_supported property
     */
    scopesSupported?: string[] | null;
    /**
     * The subject_types_supported property
     */
    subjectTypesSupported?: string[] | null;
    /**
     * The token_endpoint property
     */
    tokenEndpoint?: string | null;
    /**
     * The userinfo_endpoint property
     */
    userinfoEndpoint?: string | null;
}
/**
 * Serializes information the current object
 * @param AuthToken The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAuthToken(writer: SerializationWriter, authToken: Partial<AuthToken> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!authToken || isSerializingDerivedType) { return; }
    writer.writeStringValue("access_token", authToken.accessToken);
    writer.writeNumberValue("expires_in", authToken.expiresIn);
    writer.writeStringValue("id_token", authToken.idToken);
    writer.writeStringValue("refresh_token", authToken.refreshToken);
    writer.writeAdditionalData(authToken.additionalData);
}
/**
 * Serializes information the current object
 * @param ErrorEscaped The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorEscaped(writer: SerializationWriter, errorEscaped: Partial<ErrorEscaped> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!errorEscaped || isSerializingDerivedType) { return; }
    writer.writeStringValue("developerMessage", errorEscaped.developerMessage);
    writer.writeStringValue("errorCode", errorEscaped.errorCode);
    writer.writeStringValue("more info", errorEscaped.moreInfo);
    writer.writeStringValue("userMessage", errorEscaped.userMessage);
    writer.writeAdditionalData(errorEscaped.additionalData);
}
/**
 * Serializes information the current object
 * @param Introspecttoken The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIntrospecttoken(writer: SerializationWriter, introspecttoken: Partial<Introspecttoken> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!introspecttoken || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("active", introspecttoken.active);
    writer.writeStringValue("client_id", introspecttoken.clientId);
    writer.writeNumberValue("exp", introspecttoken.exp);
    writer.writeStringValue("scope", introspecttoken.scope);
    writer.writeStringValue("userid", introspecttoken.userid);
    writer.writeAdditionalData(introspecttoken.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Jwks The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJwks(writer: SerializationWriter, jwks: Partial<Jwks> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!jwks || isSerializingDerivedType) { return; }
    writer.writeStringValue("e", jwks.e);
    writer.writeStringValue("kid", jwks.kid);
    writer.writeStringValue("kty", jwks.kty);
    writer.writeStringValue("n", jwks.n);
    writer.writeStringValue("use", jwks.use);
    writer.writeAdditionalData(jwks.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param OidcSpec The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOidcSpec(writer: SerializationWriter, oidcSpec: Partial<OidcSpec> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!oidcSpec || isSerializingDerivedType) { return; }
    writer.writeStringValue("authorization_endpoint", oidcSpec.authorizationEndpoint);
    writer.writeCollectionOfPrimitiveValues<string>("grant_types_supported", oidcSpec.grantTypesSupported);
    writer.writeCollectionOfPrimitiveValues<string>("id_token_signing_alg_values_supported", oidcSpec.idTokenSigningAlgValuesSupported);
    writer.writeStringValue("introspection_endpoint", oidcSpec.introspectionEndpoint);
    writer.writeStringValue("issuer", oidcSpec.issuer);
    writer.writeStringValue("jwks_uri", oidcSpec.jwksUri);
    writer.writeCollectionOfPrimitiveValues<string>("response_modes_supported", oidcSpec.responseModesSupported);
    writer.writeCollectionOfPrimitiveValues<string>("response_types_supported", oidcSpec.responseTypesSupported);
    writer.writeStringValue("revocation_endpoint", oidcSpec.revocationEndpoint);
    writer.writeCollectionOfPrimitiveValues<string>("scopes_supported", oidcSpec.scopesSupported);
    writer.writeCollectionOfPrimitiveValues<string>("subject_types_supported", oidcSpec.subjectTypesSupported);
    writer.writeStringValue("token_endpoint", oidcSpec.tokenEndpoint);
    writer.writeStringValue("userinfo_endpoint", oidcSpec.userinfoEndpoint);
    writer.writeAdditionalData(oidcSpec.additionalData);
}
/**
 * Enum for grant types
 */
export const GranttypeObject = {
    Client_credentials: "client_credentials",
    Authorization_code: "authorization_code",
    Refresh_token: "refresh_token",
    UrnIetfParamsOauthGrantTypeJwtBearer: "urn:ietf:params:oauth:grant-type:jwt-bearer",
} as const;
/* tslint:enable */
/* eslint-enable */
