/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithAccountItemRequestBuilder, WithAccountItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /accounts
 */
export interface AccountsRequestBuilder extends BaseRequestBuilder<AccountsRequestBuilder> {
    /**
     * Gets an item from the Autodesk.ACC.DataConnector.accounts.item collection
     * @param accountId The account ID
     * @returns {WithAccountItemRequestBuilder}
     */
     byAccountId(accountId: Guid) : WithAccountItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AccountsRequestBuilderUriTemplate = "{+baseurl}/accounts";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AccountsRequestBuilderNavigationMetadata: Record<Exclude<keyof AccountsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byAccountId: {
        navigationMetadata: WithAccountItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["accountId"],
    },
};
/* tslint:enable */
/* eslint-enable */
