/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /authentication/v2/logout
 */
export interface LogoutRequestBuilder extends BaseRequestBuilder<LogoutRequestBuilder> {
    /**
     * This API endpoint logs a user out by removing their user browser session and redirects the user to the Autodesk login page.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     get(requestConfiguration?: RequestConfiguration<LogoutRequestBuilderGetQueryParameters> | undefined) : Promise<void>;
    /**
     * This API endpoint logs a user out by removing their user browser session and redirects the user to the Autodesk login page.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<LogoutRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * This API endpoint logs a user out by removing their user browser session and redirects the user to the Autodesk login page.
 */
export interface LogoutRequestBuilderGetQueryParameters {
    /**
     * Location to redirect once the logout is performed. Note that the provided domain host should be in the allowed list. Contact #oxygen slack channel for more details.
     */
    postLogoutRedirectUri?: string;
}
/**
 * Uri template for the request builder.
 */
export const LogoutRequestBuilderUriTemplate = "{+baseurl}/authentication/v2/logout{?post_logout_redirect_uri*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const LogoutRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "postLogoutRedirectUri": "post_logout_redirect_uri",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const LogoutRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: LogoutRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
        queryParametersMapper: LogoutRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
