/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithAccountItemRequestBuilder, WithAccountItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /construction/admin/v1/accounts
 */
export interface AccountsRequestBuilder extends BaseRequestBuilder<AccountsRequestBuilder> {
    /**
     * Gets an item from the Autodesk.ACC.AccountAdmin.construction.admin.v1.accounts.item collection
     * @param accountId The ID of the ACC account that contains the project being created or the projects being retrieved. This corresponds to the hub ID in the `Data Management API </en/docs/data/v2/>`_. To convert a hub ID into an account ID, remove the ``**b.**`` prefix. For example, a hub ID of ``b.c8b0c73d-3ae9`` translates to an account ID of ``c8b0c73d-3ae9``.
     * @returns {WithAccountItemRequestBuilder}
     */
     byAccountId(accountId: Guid) : WithAccountItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AccountsRequestBuilderUriTemplate = "{+baseurl}/construction/admin/v1/accounts";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AccountsRequestBuilderNavigationMetadata: Record<Exclude<keyof AccountsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byAccountId: {
        navigationMetadata: WithAccountItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["accountId"],
    },
};
/* tslint:enable */
/* eslint-enable */
