/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AttachmentsRequestBuilderRequestsMetadata, type AttachmentsRequestBuilder } from './attachments/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /vaults/{-id}/change-order-comments/{id}
 */
export interface ChangeOrderCommentsItemRequestBuilder extends BaseRequestBuilder<ChangeOrderCommentsItemRequestBuilder> {
    /**
     * The attachments property
     */
    get attachments(): AttachmentsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ChangeOrderCommentsItemRequestBuilderUriTemplate = "{+baseurl}/vaults/{%2Did}/change-order-comments/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ChangeOrderCommentsItemRequestBuilderNavigationMetadata: Record<Exclude<keyof ChangeOrderCommentsItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    attachments: {
        requestsMetadata: AttachmentsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
