/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createEntityCollectionFromDiscriminatorValue, createErrorResponseFromDiscriminatorValue, type EntityCollection, type ErrorResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /vaults/{-id}/folders/{id}/contents
 */
export interface ContentsRequestBuilder extends BaseRequestBuilder<ContentsRequestBuilder> {
    /**
     * Get the folder objects and children under it with the given Id in the given vault with vaultId.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<EntityCollection>}
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 403 status code
     * @throws {ErrorResponse} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<ContentsRequestBuilderGetQueryParameters> | undefined) : Promise<EntityCollection | undefined>;
    /**
     * Get the folder objects and children under it with the given Id in the given vault with vaultId.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ContentsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get the folder objects and children under it with the given Id in the given vault with vaultId.
 */
export interface ContentsRequestBuilderGetQueryParameters {
    /**
     * Indicates the state of the cursor for pagination. Use this parameter to navigate through paged results
     */
    cursorState?: string;
    /**
     * Specifies the number of results to return per page. Maximum limit is controlled by "Page size conifguration" settingwhich could be updated using ADMS ("Global Setting" -> "Page size conifguration").
     */
    limit?: number;
    /**
     * ``true``: The response will include additional detailed information for each entity. Examples include:- For folders (getFolders), it will return `FolderExtended` instead of `Folder`, which includes additional information such as the parent folder.- For file versions (getFileVersions), it will return `FileVersionExtended` instead of `FileVersion`, which includes extra details like the checkout user ID.- For change orders (getChangeOrders), it will return `ChangeOrderExtended` instead of `ChangeOrder`, which provides further information such as the list of assignees.- For property definitions (getPropertyDefinitions), it will return `PropertyDefinitionExtended` instead of `PropertyDefinition`, which includes extra details like list values.``false``: (Default) The response will include basic information for each entity.
     */
    optionextendedModels?: boolean;
    /**
     * ``true``: (Default) Include folders or folder links in the search result.``false``: Exclude folders or folder links in the search result.
     */
    optionincludeFolders?: boolean;
    /**
     * ``true``: (Default) Include Item/Change-order Link in the search result.``false``: Exclude Item/Change-order Link in the search result.
     */
    optionincludeItemEcoLinks?: boolean;
    /**
     * ``true``: (Default) Include only the latest version.``false``: Include all versions.
     */
    optionlatestOnly?: boolean;
    /**
     * The properties that need to be returned. property ids separated by ',', e.g. '1,2,3' 'all' means return all properties.
     */
    optionpropDefIds?: string;
    /**
     * ``true``: Include only file/file links that are in consumable (released) state.``false``: (Default) Include all files/file links.
     */
    optionreleasedFilesOnly?: boolean;
    /**
     * ``true``: Include only itemLink that are consumable state.``false``: (Default) Include all itemLink.
     */
    optionreleasedItemsOnly?: boolean;
    /**
     * ``true``: Search query text within all properties or both in all properties and content.``false``: (Default) Search query text within all properties.
     */
    optionsearchContent?: boolean;
    /**
     * ``true``: Search query text within all sub folders.``false``: (Default) Do not search query text within all sub folders.
     */
    optionsearchSubFolders?: boolean;
    /**
     * The value to use for the search. Based on 'SearchContent' option, this parameter will either search across all properties  or across all properties and content. Ex: q=Assembly, all objects that contain 'Assembly' within their properties will be returned. 
     */
    q?: string;
    /**
     * Specifies sorting criteria for search results. Format: {propertyDefSysName} {sort-order} Accepted values for sort-order: asc, desc.  Ex: sort = Revision desc,Name asc
     */
    sort?: string;
}
/**
 * Uri template for the request builder.
 */
export const ContentsRequestBuilderUriTemplate = "{+baseurl}/vaults/{%2Did}/folders/{id}/contents{?cursorState*,limit*,option%5BextendedModels%5D*,option%5BincludeFolders%5D*,option%5BincludeItemEcoLinks%5D*,option%5BlatestOnly%5D*,option%5BpropDefIds%5D*,option%5BreleasedFilesOnly%5D*,option%5BreleasedItemsOnly%5D*,option%5BsearchContent%5D*,option%5BsearchSubFolders%5D*,q*,sort*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const ContentsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "optionextendedModels": "option%5BextendedModels%5D",
    "optionincludeFolders": "option%5BincludeFolders%5D",
    "optionincludeItemEcoLinks": "option%5BincludeItemEcoLinks%5D",
    "optionlatestOnly": "option%5BlatestOnly%5D",
    "optionpropDefIds": "option%5BpropDefIds%5D",
    "optionreleasedFilesOnly": "option%5BreleasedFilesOnly%5D",
    "optionreleasedItemsOnly": "option%5BreleasedItemsOnly%5D",
    "optionsearchContent": "option%5BsearchContent%5D",
    "optionsearchSubFolders": "option%5BsearchSubFolders%5D",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ContentsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ContentsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createEntityCollectionFromDiscriminatorValue,
        queryParametersMapper: ContentsRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
