/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorResponseFromDiscriminatorValue, createVaultOptionCollectionFromDiscriminatorValue, createVaultOptionFromDiscriminatorValue, serializeVaultOption, type ErrorResponse, type VaultOption, type VaultOptionCollection } from '../../../models/index.js';
// @ts-ignore
import { type VaultOptionsItemRequestBuilder, VaultOptionsItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {VaultOptionsPostRequestBody}
 */
// @ts-ignore
export function createVaultOptionsPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoVaultOptionsPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @param VaultOptionsPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoVaultOptionsPostRequestBody(vaultOptionsPostRequestBody: Partial<VaultOptionsPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { vaultOptionsPostRequestBody.name = n.getStringValue(); },
        "value": n => { vaultOptionsPostRequestBody.value = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param VaultOptionsPostRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeVaultOptionsPostRequestBody(writer: SerializationWriter, vaultOptionsPostRequestBody: Partial<VaultOptionsPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!vaultOptionsPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", vaultOptionsPostRequestBody.name);
    writer.writeStringValue("value", vaultOptionsPostRequestBody.value);
    writer.writeAdditionalData(vaultOptionsPostRequestBody.additionalData);
}
export interface VaultOptionsPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * Option name
     */
    name?: string | null;
    /**
     * Option value
     */
    value?: string | null;
}
/**
 * Builds and executes requests for operations under /vaults/{-id}/vault-options
 */
export interface VaultOptionsRequestBuilder extends BaseRequestBuilder<VaultOptionsRequestBuilder> {
    /**
     * Gets an item from the Autodesk.VaultData.vaults.item.vaultOptions.item collection
     * @param id The unique identifier of an option.
     * @returns {VaultOptionsItemRequestBuilder}
     */
     byId(id: string) : VaultOptionsItemRequestBuilder;
    /**
     * Returns list of options which applies to the entire vault. 
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<VaultOptionCollection>}
     * @throws {ErrorResponse} error when the service returns a 400 status code
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 403 status code
     */
     get(requestConfiguration?: RequestConfiguration<VaultOptionsRequestBuilderGetQueryParameters> | undefined) : Promise<VaultOptionCollection | undefined>;
    /**
     * Creates a new option which applies to the particular vault
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<VaultOption>}
     * @throws {ErrorResponse} error when the service returns a 400 status code
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 403 status code
     * @throws {ErrorResponse} error when the service returns a 409 status code
     */
     post(body: VaultOptionsPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<VaultOption | undefined>;
    /**
     * Returns list of options which applies to the entire vault. 
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<VaultOptionsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Creates a new option which applies to the particular vault
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: VaultOptionsPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Returns list of options which applies to the entire vault. 
 */
export interface VaultOptionsRequestBuilderGetQueryParameters {
    /**
     * Indicates the state of the cursor for pagination. Use this parameter to navigate through paged results
     */
    cursorState?: string;
    /**
     * Filters and returns items whose names start with the specified string
     */
    filternameStarts?: string;
    /**
     * Specifies the number of results to return per page. Maximum limit is controlled by "Page size conifguration" settingwhich could be updated using ADMS ("Global Setting" -> "Page size conifguration").
     */
    limit?: number;
}
/**
 * Uri template for the request builder.
 */
export const VaultOptionsRequestBuilderUriTemplate = "{+baseurl}/vaults/{%2Did}/vault-options{?cursorState*,filter%5Bname%5D%2Dstarts*,limit*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const VaultOptionsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "filternameStarts": "filter%5Bname%5D%2Dstarts",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const VaultOptionsRequestBuilderNavigationMetadata: Record<Exclude<keyof VaultOptionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: VaultOptionsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const VaultOptionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: VaultOptionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createVaultOptionCollectionFromDiscriminatorValue,
        queryParametersMapper: VaultOptionsRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: VaultOptionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createVaultOptionFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeVaultOptionsPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
