/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithProjectItemRequestBuilder, WithProjectItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /construction/admin/v2/projects
 */
export interface ProjectsRequestBuilder extends BaseRequestBuilder<ProjectsRequestBuilder> {
    /**
     * Gets an item from the Autodesk.ACC.AccountAdmin.construction.admin.v2.projects.item collection
     * @param projectId The ID of the project. This corresponds to project ID in the `Data Management API </en/docs/data/v2/>`_. To convert a project ID in the Data Management API into a project ID in the ACC API you need to remove the ``**b.**`` prefix. For example, a project ID of ``b.a4be0c34a-4ab7`` translates to a project ID of ``a4be0c34a-4ab7``.
     * @returns {WithProjectItemRequestBuilder}
     */
     byProjectId(projectId: Guid) : WithProjectItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ProjectsRequestBuilderUriTemplate = "{+baseurl}/construction/admin/v2/projects";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ProjectsRequestBuilderNavigationMetadata: Record<Exclude<keyof ProjectsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byProjectId: {
        navigationMetadata: WithProjectItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["projectId"],
    },
};
/* tslint:enable */
/* eslint-enable */
