/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ProjectsRequestBuilderRequestsMetadata, type ProjectsRequestBuilder } from './projects/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /construction/admin/v1/accounts/{accountId}
 */
export interface WithAccountItemRequestBuilder extends BaseRequestBuilder<WithAccountItemRequestBuilder> {
    /**
     * The projects property
     */
    get projects(): ProjectsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithAccountItemRequestBuilderUriTemplate = "{+baseurl}/construction/admin/v1/accounts/{accountId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithAccountItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithAccountItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    projects: {
        requestsMetadata: ProjectsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
