/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorResponseFromDiscriminatorValue, createFileVersionCollectionFromDiscriminatorValue, type ErrorResponse, type FileVersionCollection } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /vaults/{-id}/file-versions/{id}/visualization-attachments
 */
export interface VisualizationAttachmentsRequestBuilder extends BaseRequestBuilder<VisualizationAttachmentsRequestBuilder> {
    /**
     * Get the visualization attachments for file version id.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FileVersionCollection>}
     * @throws {ErrorResponse} error when the service returns a 400 status code
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 403 status code
     * @throws {ErrorResponse} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<VisualizationAttachmentsRequestBuilderGetQueryParameters> | undefined) : Promise<FileVersionCollection | undefined>;
    /**
     * Get the visualization attachments for file version id.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<VisualizationAttachmentsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get the visualization attachments for file version id.
 */
export interface VisualizationAttachmentsRequestBuilderGetQueryParameters {
    /**
     * Indicates the state of the cursor for pagination. Use this parameter to navigate through paged results
     */
    cursorState?: string;
    /**
     * Specifies the number of results to return per page. Maximum limit is controlled by "Page size conifguration" settingwhich could be updated using ADMS ("Global Setting" -> "Page size conifguration").
     */
    limit?: number;
}
/**
 * Uri template for the request builder.
 */
export const VisualizationAttachmentsRequestBuilderUriTemplate = "{+baseurl}/vaults/{%2Did}/file-versions/{id}/visualization-attachments{?cursorState*,limit*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const VisualizationAttachmentsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: VisualizationAttachmentsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFileVersionCollectionFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
