/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithAuthTypeItemRequestBuilder, WithAuthTypeItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /groups/{id}/accounts
 */
export interface AccountsRequestBuilder extends BaseRequestBuilder<AccountsRequestBuilder> {
    /**
     * Gets an item from the Autodesk.VaultData.groups.item.accounts.item collection
     * @param authType Unique identifier of the item
     * @returns {WithAuthTypeItemRequestBuilder}
     */
     byAuthType(authType: string) : WithAuthTypeItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AccountsRequestBuilderUriTemplate = "{+baseurl}/groups/{id}/accounts";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AccountsRequestBuilderNavigationMetadata: Record<Exclude<keyof AccountsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byAuthType: {
        requestsMetadata: WithAuthTypeItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["authType"],
    },
};
/* tslint:enable */
/* eslint-enable */
